#spring.application.name=config-server

#server.port=8888

#spring.cloud.config.server.git.uri=https://github.com/YOUR-GITHUB-USERNAME/servicehub-config-repository.git
#spring.cloud.config.server.git.default-label=main

spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=file:///D:/Cloud%20Computing/ServiceHub/config-repository
spring.cloud.config.server.git.default-label=main